{
 "title": "Produto Service Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Serviço de Produtos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total de Requisições HTTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{application=\"produto-service\"}"
    }
   ]
  },
  {
   "title": "Tempo Máximo de Resposta HTTP",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{application=\"produto-service\"}"
    }
   ]
  },
  {
   "title": "Uso de Memória JVM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"produto-service\"}"
    }
   ]
  },
  {
   "title": "Uso de CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"produto-service\"}"
    }
   ]
  },
  {
   "title": "Total de Atualizações de Estoque",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "produto_service_estoque_atualizacoes_total"
    }
   ]
  },
  {
   "title": "Total de Produtos",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "produto_service_produtos_count" }
   ]
  }
 ]
}